### ISSUE TITLE
Image not saving with project

### ISSUE THREAD

**Issue by Shivy011** [ankitrohatgi/WebPlotDigitizer#239] opened 2020-12-08 10:00 UTC
Hi,

I have exported a project to .tar using the file save project.
However, the image did not save and I cannot re-overlay the image back over onto the project, it just opens a new project.

How can I ensure the image saves with the project?

Thanks

**Comment by nbehrnd** [comment] 2020-12-08 10:38
Hi,

your description is new to me because so far, once I loaded the .png
to digitize, the .tar generated by save project always included the
original image.

To clarify, may you confirm you used the digitizer as provided on the
web, https://automeris.io/WebPlotDigitizer/ ?  This is just to exclude
a maybe outdated local installation.  For comparison: when I used this
address to run the program yesterday, the .png was included.

May you append the archive of your project to complete your report?
The .tar format used by the Digitizer is not accepted by GitHub to
document issues here; however, you may enclose this into a .zip which
eventually is fine.  And apparently you have to access GitHub to
deposit the .zip directly, it won't be put in place as an attachment
of an e-mail.

**Comment by ankitrohatgi** [comment] 2021-01-13 18:30
Hi, closing due to lack of enough information to do anything about this right now. If you can share more details and a way to reproduce the problem then reopen this issue.

**Closed by ankitrohatgi** 2021-01-13 18:30 UTC
