### ISSUE TITLE
PDFs loading is not working

### ISSUE THREAD

**Issue by ItayBM** [ankitrohatgi/WebPlotDigitizer#259] opened 2021-05-24 11:54 UTC
Hello, I've been using webplotdigitizer 4.2 for a long time on mac, but I updated to 4.4 recently, and since then, when I try to load a pdf as an image, it just shows me the little rectangle with "Processing..." written on it, and doesn't actually load the image at any point. These are not complicated/heavy pdfs, so I don't know why it's not working.
When I save the pdfs as pngs, it can load the pngs just fine, so it appears the problem is with the pdf loading. 
Thanks in advance

**Comment by ankitrohatgi** [comment] 2021-05-26 03:10
Hi, are you using the downloadable version?

**Comment by ankitrohatgi** [comment] 2021-05-27 22:47
Thanks for reporting this - I was able to try this out today. It is definitely broken.

If possible, please use the online version while I find a fix.

**Comment by ItayBM** [comment] 2021-05-31 12:40
Thanks

**Comment by ewchow** [comment] 2021-06-02 20:03
I suspect this could be an issue with electron `11.0.3` and pdfjs. I haven't looked too deeply into this to figure out exactly why it's occurring, but it might be due to the interactions between the electron environment and pdfjs workers ([based on this issue](https://github.com/mozilla/pdf.js/issues/11790#issue-596701813)). The good news is when I updated to electron `12.0.9`, the PDFs loaded properly. Potential quick fix :)

**Comment by ItayBM** [comment] 2021-06-03 13:31
Great, thanks!

>

**Comment by billdenney** [comment] 2021-06-09 10:51
Is that fix as simple as changing the electron version here?

https://github.com/ankitrohatgi/WebPlotDigitizer/blob/761169369706972c1da6a6690026c1fb938ab039/electron/package.json#L15-L17

And, with the update, should we jump all the way to 13.1.0 or is there a reason to stick with the 12.x version?

**Comment by ewchow** [comment] 2021-06-18 03:15
I believe so, it should be as simple as updating the version in that package.json.

I don't think there's a reason not to jump all the way to 13.x, the PDFs loaded properly with 13.x as well during my testing.

**Comment by ankitrohatgi** [comment] 2021-06-25 04:59
Yeah I can confirm that this is just due to electron vs pdfjs version differences. I'll push a new build this weekend.

**Comment by ankitrohatgi** [comment] 2021-08-15 21:06
Should be fixed in v4.5 released recently.

**Closed by ankitrohatgi** 2021-08-15 21:06 UTC
Labels: type: bug

**Comment by superx458** [comment] 2023-07-14 14:23
Hello! I think I'm experiencing a similar issue here, but with the tar.gz files. I upload the PDF no problem, and then I digitize my data and export as tar.gz. 

The problem is that for some PDFs digitized as tar.gz, when I "Load Project" and upload the tar.gz file, some work immediately, and other tar.gz files are stuck in "Processing" forever, and I can no longer edit my data. I am using the online version, and also tried the desktop version to no luck. Any help would be awesome!

**Comment by nbehrnd** [comment] 2023-07-14 15:11
@superx458 Does this problem equally occur if you open the .pdf in a viewer (zathura, atril, you name it), *reprint* the only page with the diagram(s) of interest into a separate (single paged) as a .pdf which then in turn is submitted to the digitizer?

In case of absence of such a (virtual) printer suitable to your operating system, one alternatively split/burst the multipage pdf into individual pages (e.g., [pdftk](https://www.pdflabs.com/)), or pick the page (a selective open/save as pdf) with a heavier tool like [inkscape](https://inkscape.org/).  Depending on the journal as source of the pdf, inkscape's success to ungroup the page's elements to carve out only the diagram in question can however vary.  Though requiring a bit more (manual) work than a mere (single page) reprint into a pdf, I speculate the submission of a such a page trimmed to «only the interesting stuff» equates to less relevant content the digitizer has to manage (and eventually less file I/O with the respect to the tar.gz).

**Comment by nbehrnd** [comment] 2023-07-19 17:18
> Any ideas on how to re-retrieve this data if any? Or convert the tar.gz file into a json that I can play with?

Among the .pdf causing the problem (i.e, reload takes so long/is not successful), is there one you may share (i.e., no confidential data) as an attachment in this thread? While it is not a promise of a solution, subscribers here then were able to replicate your findings, possibly identify an improvement either in the workflow, or/and how the digitizer processes/stores the data.  (Not for the compression, but stashing the corresponding .tar.gz into a .zip archive [because only the later equally is a file format supported here] could complement the circle.)

**Comment by billdenney** [comment] 2023-07-19 17:23
@superx458, I believe that the data are stored as a .json file within the .tar.gz file.  You should be able to open with any typical decompression program (e.g. 7-zip on Windows) to find that .json file.

**Comment by nbehrnd** [comment] 2023-07-19 17:51
One path not mentioned (yet) is to read the .pdf, zoom to a scale as large as the whole diagram still is is visible and to to record a screen photo.  And to submit this .png instead of the bulky .pdf to the digitizer.
