### ISSUE TITLE
X Step won't run

### ISSUE THREAD

**Issue by Babizinho** [ankitrohatgi/WebPlotDigitizer#285] opened 2022-05-03 14:14 UTC
On my simple xy graph, "averaging window" works fine, but I need y readings for integer x values and "x step" doesn't work. When I click "Run", nothing happens. I have tried changing x step value and other changes, to no avail. How do I get "x step" to actually run?

**Comment by ankitrohatgi** [comment] 2022-05-15 05:21
closing as a duplicate of #284

**Closed by ankitrohatgi** 2022-05-15 05:21 UTC
