### ISSUE TITLE
Maximum Resolution of Image

### ISSUE THREAD

**Issue by rimpin** [ankitrohatgi/WebPlotDigitizer#38] opened 2015-02-23 19:59 UTC
First off, I love the program.  Kudos for excellent work.

What is the maximum resolution of an imagine that WPD can support?  I have a ridiculously-large image that is 39,600 x 2,475.  The image will load into WPD, but only shows a white background.  I think my option is to rescale image, but I would like to keep the image as large as possible to preserve the digitizing quality.

Thanks for your time.

**Comment by ankitrohatgi** [comment] 2015-02-23 20:08
The limit is imposed by the browser and I have seen that some do better than others and it's usually Chrome >= Firefox > Safari > IE. So it is possible that if you try Google Chrome, things work. It varies a lot from browser to browser and also with the operating system so I can't really give you exact numbers.

If a recent version of Chrome also fails then, I think you will have to resort to either cropping the relevant part out of the image, rescaling or using some compression to reduce file size (I think Safari has a file size limit in MB, not sure about Chrome).

Let me know how this goes. If it is common to see images of this size in some application, then I'd like to work on a proper solution eventually.

**Comment by ankitrohatgi** [comment] 2015-02-25 17:15
I tried with a 285Kb file with 39,600 x 2,475 (created in GIMP) and I am able to reproduce the issue you pointed. None of the browsers worked for that image. I will investigate some more and see if there's something I can fix in app. It is possible that it's a limitation imposed by the browsers.

**Comment by rimpin** [comment] 2015-02-25 17:32
I was able to open the image file in Chrome directly and the entire image displayed without the problem so I'm wasn't sure it was a limitation with the Browser.  I tested some different widths of images in WPD and found that if I resized the image below 30,000 pixels that it worked fine, but if the width was above 30,000 it would not work.

**Comment by ankitrohatgi** [comment] 2015-02-25 19:30
Thank you for sharing that! That should help in investigating the issue. Btw, what operating system are you on? Maybe Chrome behaves a little differently on some OS. I tried on Windows and 39,600 pixels didn't work.

**Comment by rimpin** [comment] 2015-02-26 21:25
I'm using Windows 7 with Chrome (40.0.2214.115 m).

**Comment by ankitrohatgi** [comment] 2015-03-10 06:00
I have tried multiple browsers on multiple operating systems and it looks like some browsers work on some operating systems and not other. There's no way for me to determine the max size and warn the user in advance, so I can't really do much here. I'm closing out this issue.

**Closed by ankitrohatgi** 2015-03-10 06:00 UTC
Labels: Bug
