### ISSUE TITLE
Remaining in "Processing..." with PDF

### ISSUE THREAD

**Issue by areftmu** [ankitrohatgi/WebPlotDigitizer#261] opened 2021-06-13 09:26 UTC
I'm using version 4.4.
Both on MAC and WINDOWS when I try to import a pdf graph, it remains in "Processing ..." and never opens the file.

**Comment by billdenney** [comment] 2021-06-18 09:57
This appears to be a duplicate of #259 .

**Comment by ankitrohatgi** [comment] 2021-08-15 21:04
Should be fixed in v4.5 released recently.

**Closed by ankitrohatgi** 2021-08-15 21:04 UTC
Labels: type: bug
