### ISSUE TITLE
Automatic Mode -> Pen highlighting

### ISSUE THREAD

**Issue by LeandroJulian** [ankitrohatgi/WebPlotDigitizer#141] opened 2018-05-02 08:45 UTC
First of all, thanks for this amazing tool. 

I just want to report a possible bug with the pen. Sometimes it refuses to select certain areas of the plot. Seems pretty much as if there were prohibited regions where it cannot work. 
I figured out that I can still use boxes so to complete my highlighting but it could be useful for you to know about this. 
Unfortunately the bugs seems to happen randomly and I'm not able to reproduce it (e.g. same figure can work or not by a simply reopening it). 
btw, I am using windows 10.

thanks for your very nice work!

**Comment by LeandroJulian** [comment] 2018-05-03 21:53
In my case I was using .png format files and I use the desktop application, version 3.8.

**Comment by ankitrohatgi** [comment] 2018-05-04 05:13
I'll take a look this weekend when I'm able to revive my Windows VM. It's possible it got fixed in version 4.1 as I changed quite a lot of code in 4.0.

**Comment by LeandroJulian** [comment] 2018-05-04 07:44
Oh, I should have tried the last version actually. I will make some test with the same images and let you know. Thank you!

**Comment by ankitrohatgi** [comment] 2018-06-16 19:03
I am not able to reproduce this. Please reopen this if you see the issue with the latest version.

**Closed by ankitrohatgi** 2018-06-16 19:03 UTC
Labels: type: bug
